FriendZone/FriendZone/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FriendZoneApp.urls')),
    path('FriendZoneApp/', include('password_reset.urls'))
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FriendZone/FriendZoneApp/urls.py
from django.urls import path
#from django.contrib.auth.views import (password_reset, password_reset_done, password_reset_confirm, password_reset_complete)
from.import views
app_name='fz'

urlpatterns = [
    path('', views.login_view),
    path('register/', views.register, name='register'),
    path('register2/', views.register2, name='register2'),
    path('index/', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<int:userProfileID>', views.profile_view, name='profile'),
    path('editprofile/', views.editprofile_view, name='editprofile'),
    path('password/', views.forgotpassword_view, name='forgotpassword'),
    path('addFriend/<int:userProfileID>/<int:newFriendID>/', views.addFriend, name='addFriend'),
    path('removeFriend/<int:userProfileID>/<int:friendID>/', views.removeFriend, name='removeFriend'),
    path('addHobby/<int:userProfileID>/<hobb>', views.addHobby, name='addHobby'),
    path('filterUsers/', views.filterUsers, name='filterUsers'),
    path('friends/<int:userProfileID>', views.listFriends, name='listFriends')
]

FriendZone/FriendZoneApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class HobbyManager(models.Manager):
    def get_by_natural_key(self, hobby):
        return self.get(hobby=hobby)

class Hobby(models.Model):
    objects = HobbyManager()

    hobby = models.CharField(max_length= 20, choices = (('Gaming', 'Gaming'), ('Sports', 'Sports'), 
    ('Reading', 'Reading'), ('Hiking', 'Hiking'), ('Cycling', 'Cycling'), ('Photography', 'Photography'), 
    ('Modelling', 'Modelling')), blank = True)

    def __str__(self):
        return self.hobby

    def natural_key(self):
        return (self.hobby)

class UserProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length = 254)
    last_name = models.CharField(max_length = 254)
    gender = models.CharField(max_length = 1, choices = (('M', 'Male'), ('F', 'Female')), blank = True)
    age = models.PositiveIntegerField(blank = True, null = True)
    image = models.ImageField(default = 'default.jpg', upload_to='media/profile_images', blank = True)
    dob = models.DateField(blank = True, null = True)
    email = models.EmailField(blank = True, unique = True)
    hobby = models.ManyToManyField(Hobby, blank = True)
    friend = models.ManyToManyField('self', blank = True)
    profileBio = models.CharField(max_length=254, blank = True)
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

FriendZone/FriendZoneApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from FriendZoneApp.models import UserProfileModel
from django.contrib.auth import authenticate
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

class EditProfileForm(UserChangeForm):
    class Meta:
        model = UserProfileModel
        fields = [
            'email',
            'first_name',
            'last_name',
            'gender',
            'image',
            'hobby',
            'profileBio'
        ]


class DateInput(forms.DateInput):
    input_type = 'date'

class RegisterForm(forms.ModelForm):

    class Meta:
        model = UserProfileModel
        # Add all the fields you want a user to change
        fields = [
            'email',
            'first_name',
            'last_name',
            'gender',
            'image',
            'hobby',
            'dob'
        ]
        widgets = {'dob' : DateInput()}

    

FriendZone/FriendZoneApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, logout
from FriendZoneApp.models import UserProfileModel, Hobby
from django.template import loader
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User
from FriendZoneApp.forms import EditProfileForm, RegisterForm
from datetime import date
from django.core import serializers
from django.core.mail import send_mail
import operator
from django.contrib.auth.decorators import login_required

# login decorator needed for specific views to be accessible

#index used to display similar users with similar hobbies as logged in user
@login_required
def index(request):
    user = request.user
    userProfile = UserProfileModel.objects.get(user = user)
    userHobbies = userProfile.hobby
    otherUserProfiles = UserProfileModel.objects.exclude(user = request.user) #excluding logged in user
    similarUsers = []
    
    #for loops to add users who have at least 1 same hobby as the logged in user and add them to the list
    for a in otherUserProfiles:
        theirHobbies = a.hobby
        for aH in theirHobbies.all():
            for uH in userHobbies.all():
                if aH==uH:
                    similarUsers.append(a)    

    sortedUsers = []
    copySimUsers = similarUsers[:]

    #creating temporary dictionaries to display the data in html template
    for sUser in copySimUsers: 
        temp = {
            0: sUser.id,
            1: sUser.first_name, 
            2: sUser.last_name, 
            3: sUser.hobby.all(),
            'count': sUser.hobby.all().count()
        }
        sortedUsers.append(temp) #adding dictinary to the list

    sortedUsers.sort(key=operator.itemgetter('count'), reverse = True) #sorting the users in the list by count of hobbies
    #and sorting them in descending order
    
    #context to display the data in the html template
    context = {
        'loggedInUser' : user,
        'userProfile' : userProfile,
        'similarUsers' : similarUsers,
        'oUP' : otherUserProfiles,
        'sortedUsers': sortedUsers
    }
    return render(request, 'FriendZoneApp/index.html', context) # rendering required page with the context needed


#method to find users by age and/or gender
def filterUsers(request):
    gender = request.GET['gender'] #chosen gender from Ajax request
    ageFilter = request.GET['chosenAge'] #chosen age from Ajax request

    user = request.user
    userProfile = UserProfileModel.objects.get(user = user)
    userHobbies = userProfile.hobby
    otherUserProfiles = UserProfileModel.objects.exclude(user = request.user)
    similarUsers = []

    #adds each user if they meet certain condtitions such as age range
    for a in otherUserProfiles:
        if a.gender==gender or gender=="test":
            theirHobbies = a.hobby
            for aH in theirHobbies.all():
                for uH in userHobbies.all():
                    if aH==uH:
                        if ageFilter == "":
                            similarUsers.append(a)    
                        else:
                            if ageFilter=="lessThan10":
                                if a.age < 10:
                                    similarUsers.append(a)
                                    print("This user age in lessThan10")
                                    print(a.age)
                            elif ageFilter=="11-20":
                                if a.age > 10 and a.age < 21:
                                    similarUsers.append(a)
                                    print("This user age in 11-20")
                                    print(a.age)
                            elif ageFilter=="21-30":
                                if a.age > 20 and a.age < 31:
                                    similarUsers.append(a)
                                    print("This user age in 21-30")
                                    print(a.age)
                            elif ageFilter=="31-40":
                                if a.age > 30 and a.age < 41:
                                    similarUsers.append(a)
                                    print("This user age in 31-40")
                                    print(a.age)
                            elif ageFilter=="moreThan41":
                                if a.age > 40:
                                    similarUsers.append(a)
                                    print("this user age in moreThan41")
                                    print(a.age)

    allProfiles = serializers.serialize("json", similarUsers, indent = 2, use_natural_foreign_keys=True, 
    use_natural_primary_keys=True) #serialising into JSON form
    return JsonResponse(allProfiles, safe=False) # returnign JSON response

#method to create a new user 
def register(request):
    if request.method == 'POST':
        #uses a post method from html template
        form = UserCreationForm(request.POST)
        #if valid it will save the form 
        if form.is_valid():
            user = form.save()
            #adds a new user in the model
            UserProfileModel.objects.create(user = user)
            #log user in 
            login(request, user)
            #redirects to the 2nd register page
            return redirect('/register2/')
    else: 
        form = UserCreationForm()
    return render (request, 'FriendZoneApp/register.html', {'form': form,'pageTitle': '- Register'})

#method to validate user login
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid(): 
            #log the user in 
            user = form.get_user()
            login(request, user) #built in log in
            return redirect('/index/')
    else: 
        form = AuthenticationForm() #if not POST, then it will be empty
    return render (request, 'FriendZoneApp/login.html', {'form': form, 'pageTitle': '- Login'})

#method to log user out
def logout_view(request):
    if request.method == 'POST':
        logout(request) #built in log out
        return redirect('/login/')

#method to view a users profile
@login_required
def profile_view(request, userProfileID):
    userProfile = UserProfileModel.objects.get(id = userProfileID) #acquring user profile of a user to view their profile
    context = {
        'userProfile' : userProfile
    }
    return render(request, 'FriendZoneApp/profile.html', context) #rendering the generic profile page, displaying contents of the context

# method to add a friend (user profile) to another user
@login_required
def addFriend(request, userProfileID, newFriendID):
    userProfile = UserProfileModel.objects.get(id = userProfileID) # acquring logged in users profile object
    newFriendProfile = UserProfileModel.objects.get(id = newFriendID) # acquiring profile object of person to add as friend
    friendName = userProfile.user # used to display user in email when sent
    userProfile.friend.add(newFriendProfile) # adding the new user to logged in users friends list to database 

    #sending the email
    send_mail('You have a new friend - FriendZone', str(friendName) + ' added you as a friend', 'friendzone720@gmail.com', recipient_list=[newFriendProfile.email])
    return index(request) # going back to index.html 

#method to add a hobby to logged in user's user profile 
@login_required
def addHobby(request, userProfileID, hobb):
    userProfile = UserProfileModel.objects.get(id = userProfileID) # acquring logged in user's user profiile
    hobby = Hobby.objects.get(hobby=hobb) # acquring the hobby object needed from database
    userProfile.hobby.add(hobby) # adding the hobby object to users user profile 
    userProfile.save() # saving changes to database
    return index(request)

#method that allows users to edit thier profiles.
@login_required
def editprofile_view(request):
    if request.method == 'POST':
        #uses ac custom django form from forms.py
        form = EditProfileForm(request.POST, instance = UserProfileModel.objects.get(user = request.user))
        if form.is_valid():  #if valid it saves it and if it contains an image it will then save it in the model and direct to index
            updated_profile = form.save()
            if 'image' in request.FILES:
                updated_profile.image = request.FILES['image']
            updated_profile.save()
            return redirect('/index/')

    else:
        form = EditProfileForm(instance = UserProfileModel.objects.get(user = request.user))
        args = {'form': form}
        return render(request, 'FriendZoneApp/editprofile.html', args)

#this is the 2nd stage of user registration
def register2(request):
    if request.method == 'POST':
        #uses a custom django form which is called from forms.py
        form = RegisterForm(request.POST, instance = UserProfileModel.objects.get(user = request.user))
        if form.is_valid():  #if form is valid then it will save in updated_profile, and if the form contains an image, then it will save to the model database
            updated_profile = form.save()
            if 'image' in request.FILES:
                updated_profile.image = request.FILES['image']
            updated_profile.save()
            #gets the current user details and then calculates the age from the DOB stored in the model
            member = UserProfileModel.objects.get(user = request.user)
            dob = member.dob
            dobYear = member.dob.year
            dobMonth = member.dob.month
            dobDay = member.dob.day
            #imports datetime to calculate current date
            today = date.today()
            ageAns = today.year - dobYear - ((today.month, today.day) < (dobMonth, dobDay))

FriendZone/FriendZoneApp/templates/FriendZoneApp/editprofile.html
{% extends "FriendZoneApp/header.html" %}
{% load crispy_forms_tags %}
{% block content %}
<body>

  <div class = "container">
    <div class = "col-xs-6 col-xs-offset-3">

    <div class="panel panel-default"
    <div class="panel-heading">
    <div class = "panel-body">
<form method = "POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <center><button class = "btn btn-default" value = "submit">Submit</button></center>
</form>
    </div>
    </div>
    </div>



{% endblock %}
</div>
</body>

FriendZone/FriendZoneApp/templates/FriendZoneApp/friends.html
{% extends "FriendZoneApp/header.html" %}
{% block content %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'friends.css' %}"/>
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <div class="container">
        <center>
      <!-- Page Heading -->
        <h1 class="my-4">My Friends
        </h1>
        </center>

        {% for friends in userFriends.all %}
            <div class="row">
                <div class="col-md-7">
                <center> 
                <br>
                <br>
                    <img class="img-fluid rounded mb-3 mb-md-0" src="{{ friends.image.url }}" alt="" width = "200">
                </a>
                </center>
            </div>
            <div class="col-md-1">
                <br></br><h3><a href="/profile/{{ friends.id }}"> {{ friends }}</a></h3>
                <a class="btn btn-danger btn-sm" href= "/removeFriend/{{ userProfile.id }}/{{ friends.id }}">Remove Friend</a>
            </div>
        {% endfor %}
    </div>
    <br><br><br><br>
    </div>

{% endblock %}

FriendZone/FriendZoneApp/templates/FriendZoneApp/header.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'FriendZoneApp/headerStyle.css' %}" />
          <link rel="stylesheet" type="text/css" href="{% static 'FriendZoneApp/styles.css' %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
       <title>{{ pageTitle }}</title>
    </head>

    <body>

    <div class="container" id = "headerBar">
        <div id = "logoStyle">
            <a href="/index"> <img src = "{% static 'logo.png' %}" height = 100> </a>
        </div>

        <p id="title">FriendZone {{ pageTitle }}  </p>

        <nav id='navlinks'>

            {% if user.is_authenticated %}
            {% else %}
            {% endif %}

            <form class='logout-link' action="/logout/" method='POST'>
                {% csrf_token %}
                {% if user.is_authenticated %}

                    <a href="/friends/1", views.friends_view, name="friends" class="btn btn-default">Friends  </a> &nbsp;
                    <a href="/profile/{{ userProfile.id }}", view.profile_view, name="profile" class="btn btn-default">Profile</a>
                    <button class = "btn btn-default" type="submit" class="logoutButton"> Log out </button>

                {% endif %}
            </form>
        </nav>


    {% if user.is_authenticated %}
        Welcome <b>{{ loggedInUser }}  <br/> <b/>
    {% else %}
        <p>Please log in</p>
    {% endif %}

    {% block content %}
    {% endblock %}
</div>
    </body>
</html>

FriendZone/FriendZoneApp/templates/FriendZoneApp/index.html
{% extends "FriendZoneApp/header.html" %}
{% block content %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
        <a href="/profile/{{ userProfile.id }}"> My Profile </a>

    <div class = "container">

      <div class="container">
        <center/>
        <div class = "main">
        <h3> Find friends with similar hobbies </h3> 

        Filter Gender:
         <input type='radio' id='maleFilter' name='genderFilter' value='F'> Female
          <input type='radio' id='femaleFilter' name='genderFilter' value='M'> Male

            <br/>

          Filter Age:
          <input type='radio' id='lessThan10' name='ageFilter' value='lessThan10'> &lt; 10
          <input type='radio' id='11-20' name='ageFilter' value='11-20'> 11-20
          <input type='radio' id='21-30' name='ageFilter' value='21-30'> 21-30
          <input type='radio' id='31-40' name='ageFilter' value='31-40'> 31-40
          <input type='radio' id='moreThan41' name='ageFilter' value='moreThan41'> &gt; 41
            <br/>

        <center> <button class="btn btn-success" id='filterButton'>Filter</button> <center/>
        </div>
      </div>

          <div class ="container">

        <div class="table-responsive">
        <table class ="table table-hover" id='table' border="solid">
          <thead>
            <tr>
                <th scope="col">Users</th>
                <th scope="col">Hobbies</th>
                <th scope="col">Add Friend?</th>
            </tr>
          </thead>
        {% for member in sortedUsers %}
            <tr>
                <td class="active"> <a href="/profile/{{ member.0 }}"> {{ member.1 }} {{ member.2 }}</a> </td>
                <td class="active">
                    {% for h in member.3 %}
                        {{ h }},
                    {% endfor %}
                </td>
                <td class="active"> <a href= "/addFriend/{{ userProfile.id }}/{{ member.0 }}" ><center><button id= 'addFriendButton' class ="btn btn-info" onclick="confirm()"> Add Friend </button><center/> </a> </td>
            </tr>
        {% endfor %}
        </table>
        </div>
        
      </div>
        <textarea id='userProfileIDLabelled'>{{ userProfile.id }}</textarea>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> </script>
<script>

$(document).ready(function(){
    $("#userProfileIDLabelled").hide();
});


$('#filterButton').click(function(e){
            var chosenAge = "";
            if ($('input[name=ageFilter]:checked').length>0 ){
                if ($('#lessThan10')[0].checked ){
                    chosenAge = $('#lessThan10')[0].value
                    console.log("Chosen Age: "+ chosenAge)
                }
                else if ($('#11-20')[0].checked ){
                    chosenAge = $('#11-20')[0].value
                    console.log("Chosen Age: "+ chosenAge)
                }
                else if ($('#21-30')[0].checked ){
                    chosenAge = $('#21-30')[0].value
                    console.log("Chosen Age: "+ chosenAge)
                }
                else if ($('#31-40')[0].checked ){
                    chosenAge = $('#31-40')[0].value
                    console.log("Chosen Age: "+ chosenAge)
                }
                else if ($('#moreThan41')[0].checked ){
                    chosenAge = $('#moreThan41')[0].value
                    console.log("Chosen Age: "+ chosenAge)
                }
            }
            else {
                console.log("IT WAS NOT CHECKED CUZ");
            }

            var chosenOption = "test";
            if ($("#maleFilter")[0].checked ){
                chosenOption = $("#maleFilter")[0].value;
            }
            else if ($("#femaleFilter")[0].checked ) {
                chosenOption = $("#femaleFilter")[0].value;
            }
            var userID = $("#userProfileIDLabelled").val();
            $.ajax({
                type: 'GET',
                url: '/filterUsers',
                data: {
                        gender : chosenOption,
                        chosenAge : chosenAge
                },
                success: function(data){
                    console.log(data);
                    var tbl = document.getElementById('table');
                    //if(tbl) tbl.parentNode.removeChild(tbl);
                    var obj = JSON.parse(data);
                    console.log(obj);


                    $('#table tr').remove();
                    for (var i=0; i<2; i++){
                        console.log(obj)
                        $('#table').append("<tr><td> <a href='/profile/" + obj[i].pk + "'> "+ obj[i].fields.first_name + " " + obj[i].fields.last_name +"</a> </td> <td> " + obj[i].fields.hobby + "</td> <td> <a href='/addFriend/" + userID + "/" + obj[i].pk + "'> <button id= 'addFriendButton' class ='btn btn-info'> Add Friend </button> </a> </td> </tr>");
                        //addHandlers();
                    }
                    
                },
                //error: function(request,msg,error) {
                    //alert('Saink in updating (PUT) went wrong!');
                //}
            })
        });

//function addHandlers(){
    function confirm(){
        alert("Friend added!");
    }
//}
//$(addHandlers);
</script>

{% endblock %}

FriendZone/FriendZoneApp/templates/FriendZoneApp/likes.html
{% extends "FriendZoneApp/header.html" %}

{% block content %}
    
    Logged in Users Profile ID: {{ userMember.id }}

    likes: {{ userLikes }}

    <h2>All users:</h2>
    {% for member in userLikes %}
        <p>{{ member }}</p>
    {% endfor %}


{% endblock %}

FriendZone/FriendZoneApp/templates/FriendZoneApp/login.html
{% extends "FriendZoneApp/header.html" %}
{% extends "FriendZoneApp/styles.css"}
{% block content %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <div class = "container">
      <div class = "col-xs-4 col-xs-offset-4">
        <div class="panel panel-primary">
        <div class="panel-heading">Login</div>
        <div class = "panel-body">

    <form class="login-form" action="{% url 'fz:login' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <center><input class = "btn btn-info btn-block" type="submit" value="Login"> </center><br/>
        <a href='/register/', views.register_view, name='register' class="btn btn-warning btn-block" role="button">Register</a>
    </form>

    </div>


      </div>
      </div>
    </div>
{% endblock %}
</body>

FriendZone/FriendZoneApp/templates/FriendZoneApp/password.html
{% extends "FriendZoneApp/header.html" %}
{% block content %}

<form method = "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Submit</button>
</form>

{% endblock %}

FriendZone/FriendZoneApp/templates/FriendZoneApp/profile.html
{% extends "FriendZoneApp/header.html" %}
{% block content %}
{% load staticfiles %}
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'profileStyle2.css' %}"/>


<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
                {% if userProfile %}
                    {% if userProfile.image %}
                        <img src="{{ userProfile.image.url }}" class="img-responsive" alt="">
                    {% else %}
                        <img src = "/media/default.jpg" class="img-responsive" alt="">
                    {% endif %}
                {% else %}
                    Error 1628 : Profile Image Error
                {% endif %}
					
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						{{ userProfile.first_name }} {{ userProfile.last_name }}
					</div>
					<div class="profile-gender-age">
                        {% if userProfile.gender == 'M' %}
                            Gender: Male &nbsp Age: {{ userProfile.age }} 
                        {% elif userProfile.gender == 'F' %}
                            Gender: Female &nbsp Age: {{ userProfile.age }} 
                        {% endif %}
            <br>
              {{ userProfile.email }}
            </br>
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
                    <a href='/friends/1', class="btn btn-success btn-sm" role="button">Friends</a>
                    <a href='/index/', class="btn btn-danger btn-sm" role="button">Home</a>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
						<li>
							<a href='/editprofile/', views.editprofile_view, name='editprofile'>
							<i class="glyphicon glyphicon-user"></i>
							Account Settings </a>
						</li>
						<li>
							<a href='/editprofile/', views.editprofile_view, name='editprofile'>
							<i class="glyphicon glyphicon-ok"></i>
							Add bio </a>
						</li>

					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>

		<div class="col-md-9">
      <div class="profile-hobbies-heading">
        <div class="profile-hobbies-title">
                  <strong>Profile</strong>
        </div>
      </div>

      <div class="profile-content">
        <h3>Bio:</h3>
        <h4>{{ userProfile.profileBio }}</h4>
        <br>
        <h3>Hobbies:</h3>
        {% for h in userProfile.hobby.all %}
            <h4>{{ h.hobby }}</h4>
            {% endfor %}
            <div class="profile-userbuttonsAddHobbie">
              <a href='/editprofile/', views.editprofile_view, name='editprofile' class="btn btn-success btn-sm" role="button">Add hobbies</a>
    				</div>
      </div>
		</div>
	</div>
</div>
<center>
<strong>Powered by ITL'S FINEST<a href="" target="_blank"></a></strong>
</center>
<br>
<br>

{% endblock %}

FriendZone/FriendZoneApp/templates/FriendZoneApp/register.html
{% extends "FriendZoneApp/header.html" %}
{% load crispy_forms_tags %}
{% block content %}

<body>

 <div class = "container">
   <div class = "col-xs-6 col-xs-offset-3">
      <div class = "panel panel-primary ">
       <div class="panel-heading">Register</div>
        <div class = "panel-body">
   <form class="register-form" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input class ="btn btn-success btn-block" type="submit" value="Register">
      </form>

        </div>
      </div>
   </div>

{% endblock %}
</body>

FriendZone/FriendZoneApp/templates/FriendZoneApp/register2.html
{% extends "FriendZoneApp/header.html" %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'registerStyle.css' %}"/>
{% load crispy_forms_tags %}
{% block content %}
<body>

  <div class = "container">
    <div class = "col-xs-6 col-xs-offset-3">
    <div class="panel panel-default"
    <div class="panel-heading">Please input your information</div>
    <div class = "panel-body">
<form method = "POST">
    {% csrf_token %}
    {{ form|crispy }}

    <center><button class = "btn btn-default" value = "submit">Submit</button></center>
</form>
    </div>

    </div>



{% endblock %}
</div>
</body>